import { Router } from 'express';
import { authRoutes } from './modules/auth/auth.routes.js';
import { userRoutes } from './modules/users/user.routes.js';
import { teamRoutes } from './modules/teams/team.routes.js';
import { projectRoutes } from './modules/projects/project.routes.js';
import { incidentRoutes } from './modules/incidents/incident.routes.js';
import { techDebtRoutes } from './modules/techDebt/techDebt.routes.js';
import { architectureRoutes } from './modules/architecture/architecture.routes.js';
import { oneOnOneRoutes } from './modules/oneOnOnes/oneOnOne.routes.js';
import { dashboardRoutes } from './modules/dashboard/dashboard.routes.js';
import { aiRoutes } from './modules/ai/ai.routes.js';
import { financeRoutes } from './modules/finance/finance.routes.js';
import { orgRoutes } from './modules/org/org.routes.js';
import { okrRoutes } from './modules/okrs/okr.routes.js';
import { investmentRoutes } from './modules/investment/investment.routes.js';
import { briefRoutes } from './modules/brief/brief.routes.js';
import { scorecardRoutes } from './modules/scorecard/scorecard.routes.js';
import { engagementRoutes } from './modules/engagement/engagement.routes.js';
import { integrationRoutes } from './integrations/integration.routes.js';

export const apiRouter = Router();

apiRouter.use('/auth', authRoutes);
apiRouter.use('/users', userRoutes);
apiRouter.use('/teams', teamRoutes);
apiRouter.use('/projects', projectRoutes);
apiRouter.use('/incidents', incidentRoutes);
apiRouter.use('/tech-debt', techDebtRoutes);
apiRouter.use('/architecture', architectureRoutes);
apiRouter.use('/one-on-ones', oneOnOneRoutes);
apiRouter.use('/dashboard', dashboardRoutes);
apiRouter.use('/ai', aiRoutes);
apiRouter.use('/finance', financeRoutes);
apiRouter.use('/org', orgRoutes);
apiRouter.use('/okrs', okrRoutes);
apiRouter.use('/investment', investmentRoutes);
apiRouter.use('/brief', briefRoutes);
apiRouter.use('/scorecard', scorecardRoutes);
apiRouter.use('/engagement', engagementRoutes);
apiRouter.use('/integrations', integrationRoutes);
